### PR TITLE
Target netstandard2.0

### PR DESCRIPTION
**Pull request by spewu**
Updated the project to target netstandard2.0. Could not pick a lower netstandard version, as that would have required a larger rewrite. This is a very simple change to allow the library to be used in .NET Core projects.

### CODE REVIEW

**Comment by brameye** [comment]
Any way this could be merged into master and added to the official nuget? Currently working on a dotnetcore project where it would be very useful. @alexreinert 

Thanks!

**Comment by afriedma** [comment]
@alexreinert hello,  I am also trying to use the library with dotnetcore 2.1, is there any way you can release it to nuget soon?

**Comment by AlexTalavari** [comment]
We are planning to use it soon. Currently we are implementing a custom project based on the source code but it would be nice to get rid of it in favor of an official Nuget Package

**Comment by Nuklon** [comment]
@alexreinert I see you're active on GitHub, could you merge this or add some collaborators to help merge the PRs.

**Comment by AlexTalavari** [comment]
@alexreinert  If you are retired of the project please add more collaborators and allow the project to flourish. It's gonna be the building block of a new project. Currently we have been using a clone of the repo ported to .NetCore, It would be nice to have the original repo update otherwise we can always fork it. @ststeigerwe can always use your port and update it but my company wants a nuget package.

**Comment by ststeiger** [comment]
Pff, I had it on .NET Core 1.1  => https://github.com/ststeiger/Arsoft
It's really not very difficult to get it to work on a lower version...
Maybe learn to google...

**Comment by AlexTalavari** [comment]
@ststeiger  outside of the test server your repo is 2 years old.  And this repo has changes from 1 year ago. There are active PRs that have not been merged and there is no nuget package in your repo that links to your version. I am sorry but we can not trust any nuget that does not correspond to the latest version here or on your repos. 

As for nugets there is this one

by: mccj
https://www.nuget.org/packages/ARSoft.Tools.Net.Core/
with 141 downloads (at the time when i write this) and version 2.3

by: TechnikEmpire
https://www.nuget.org/packages/ARSoft.Tools.Net.NetCore/
with 637 downloads (at the time when i write this) and version 1.0

by: dxsdata
https://www.nuget.org/packages/ARSoft.Tools.NetStandard.DXSdata/
with 2,931 downloads (at the time when i write this) and version 1.0

by: Tiny
https://www.nuget.org/packages/ARSoft.Tools.Net.CoreClr/
with 1034 downloads (at the time when i write this) and version 1.0

And the one from this repo
https://www.nuget.org/packages/ARSoft.Tools.Net/
with 205,695 downloads (at the time when i write this) and version 2.2.9


I don't see your username so how can we use yours?

Also the version mismatch is also a problem. 
mccj has the only one with a logical continuation of this repo but the namespaces are different

The best solution is to port this repo to net core  and use the official nugets as 2.3
 @alexreinert i hope you see where we coming from and allow other people assist you maintaining this repo

**Pull request closed without merging**
